# Generated by Django 5.1.1 on 2025-04-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0002_alter_booking_check_in_alter_booking_check_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
