# Generated by Django 5.1.1 on 2025-04-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
