# Generated by Django 5.1.1 on 2025-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0004_room_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Debit Card', 'Debit In')], default='Cash', max_length=50, null=True),
        ),
    ]
